#include "polish_glue.hpp"
#include <htslib/sam.h>
#include <zlib.h>
#include <algorithm>
#include <cctype>
#include <fstream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <tuple>
#include <utility>
#include <vector>
namespace fs=std::filesystem;
namespace subass { namespace {
using Fasta=std::map<std::string,std::string>;
Fasta readfa(const fs::path&p){std::ifstream f(p);if(!f)throw std::runtime_error("open FASTA: "+p.string());Fasta x;std::string l,id;while(std::getline(f,l)){if(!l.empty()&&l.back()=='\r')l.pop_back();if(l.empty())continue;if(l[0]=='>'){id=l.substr(1);auto q=id.find_first_of(" \t");if(q!=std::string::npos)id.resize(q);x[id];}else for(char c:l)if(!std::isspace((unsigned char)c))x[id]+=std::toupper((unsigned char)c);}return x;}
void write_record(std::ostream&out,const std::string&id,const std::string&sequence){out<<'>'<<id<<'\n';for(size_t i=0;i<sequence.size();i+=60){const auto n=std::min<size_t>(60,sequence.size()-i);out.write(sequence.data()+i,n);out.put('\n');}}
std::vector<std::string> split(const std::string&s,char d='\t'){std::vector<std::string>v;std::stringstream q(s);std::string z;while(std::getline(q,z,d))v.push_back(z);return v;}
std::string rc(std::string s){for(char&c:s){if(c=='A')c='T';else if(c=='C')c='G';else if(c=='G')c='C';else if(c=='T')c='A';else c='N';}std::reverse(s.begin(),s.end());return s;}
struct Hit{std::string q,t;int qs=0,qe=0,ql=0,ts=0,te=0;bool rev=false;};
std::vector<Hit> hits(const fs::path&bam){const auto path=bam.string();samFile*f=sam_open(path.c_str(),"r");if(!f)throw std::runtime_error("open BAM");bam_hdr_t*h=sam_hdr_read(f);bam1_t*b=bam_init1();std::vector<Hit>v;while(sam_read1(f,h,b)>=0){if(b->core.flag&BAM_FUNMAP)continue;Hit z;z.q=bam_get_qname(b);z.t=h->target_name[b->core.tid];z.ts=b->core.pos;z.te=bam_endpos(b);z.rev=b->core.flag&BAM_FREVERSE;int hardL=0,hardR=0,softL=0,softR=0,q=0;auto*c=bam_get_cigar(b);bool left=true;for(uint32_t i=0;i<b->core.n_cigar;i++){int op=bam_cigar_op(c[i]),n=bam_cigar_oplen(c[i]);if(op==BAM_CHARD_CLIP){if(left)hardL+=n;else hardR+=n;}else{left=false;if(op==BAM_CSOFT_CLIP){if(i==0)softL=n;else softR=n;}if(bam_cigar_type(op)&1)q+=n;}}z.qs=hardL+softL;z.qe=q+hardL-softR;z.ql=z.qe+hardR;v.push_back(std::move(z));}bam_destroy1(b);bam_hdr_destroy(h);sam_close(f);return v;}
}
static ComposeResult compose_consensus_impl(const fs::path&in,const fs::path&out,const std::unordered_map<std::string,int>&cov,const fs::path&stats,const fs::path&bed,bool retain_result){std::ifstream f(in);if(!f)throw std::runtime_error("open consensus");std::map<std::string,std::vector<std::tuple<int,int,int,std::string>>> all;std::string h,s;while(std::getline(f,h)){if(!std::getline(f,s))throw std::runtime_error("odd consensus lines");auto t=split(h,' ');if(t.size()!=4||h.empty()||h[0]!='>')throw std::runtime_error("consensus format");all[h.substr(1,h.find(' ')-1)].push_back({std::stoi(t[1]),std::stoi(t[3]),std::stoi(t[2]),std::move(s)});}ComposeResult r;const auto bed_path=bed.string();gzFile gz=gzopen(bed_path.c_str(),"wb");if(!gz)throw std::runtime_error("create coverage BED: "+bed.string());std::ofstream fa(out);if(!fa){gzclose(gz);throw std::runtime_error("create FASTA: "+out.string());}std::ofstream st(stats);if(!st){gzclose(gz);throw std::runtime_error("create stats: "+stats.string());}gzprintf(gz,"#seq_name\tstart\tend\tcoverage\n");st<<"#seq_name\tlength\tcoverage\n";for(auto&kv:all){auto&v=kv.second;std::sort(v.begin(),v.end());size_t total=0;for(const auto&z:v)total+=std::get<3>(z).size();std::string sequence;sequence.reserve(total);int pos=0;for(auto&z:v){const auto&x=std::get<3>(z);sequence+=x;gzprintf(gz,"%s\t%d\t%d\t%d\n",kv.first.c_str(),pos,pos+(int)x.size(),std::get<2>(z));pos+=x.size();}v.clear();v.shrink_to_fit();write_record(fa,kv.first,sequence);auto it=cov.find(kv.first);st<<kv.first<<'\t'<<sequence.size()<<'\t'<<(it==cov.end()?0:it->second)<<'\n';if(retain_result){r.lengths[kv.first]=pos;r.sequences.emplace(kv.first,std::move(sequence));}}gzclose(gz);return r;}
ComposeResult compose_consensus(const fs::path&in,const fs::path&out,const std::unordered_map<std::string,int>&cov,const fs::path&stats,const fs::path&bed){return compose_consensus_impl(in,out,cov,stats,bed,true);}
void compose_consensus_to_files(const fs::path&in,const fs::path&out,const std::unordered_map<std::string,int>&cov,const fs::path&stats,const fs::path&bed){(void)compose_consensus_impl(in,out,cov,stats,bed,false);}
void filter_subassembly_coverage(const fs::path&statsIn,const fs::path&contigsIn,const fs::path&statsOut,const fs::path&contigsOut){std::ifstream f(statsIn);std::map<std::string,std::pair<int,int>>s;std::string l;while(std::getline(f,l))if(!l.empty()&&l[0]!='#'){auto t=split(l);s[t[0]]={std::stoi(t[1]),std::stoi(t[2])};}auto in=readfa(contigsIn);std::ofstream st(statsOut);if(!st)throw std::runtime_error("create stats: "+statsOut.string());std::ofstream out(contigsOut);if(!out)throw std::runtime_error("create FASTA: "+contigsOut.string());st<<"#seq_name\tlength\tcoverage\n";for(auto&kv:in){const auto&entry=s.at(kv.first);if(entry.second>=1){write_record(out,kv.first,kv.second);st<<kv.first<<'\t'<<entry.first<<'\t'<<entry.second<<'\n';}}}
void generate_polished_gfa(const fs::path&edges,const fs::path&gfa,const fs::path&polished,const fs::path&bam,const fs::path&out){auto ed=readfa(edges),ctg=readfa(polished);std::map<std::string,std::vector<Hit>>by;auto all_hits=hits(bam);for(auto&h:all_hits){std::string key=h.q;by[std::move(key)].push_back(std::move(h));}all_hits.clear();all_hits.shrink_to_fit();for(auto&kv:ed){auto it=by.find(kv.first);if(it==by.end())continue;auto&v=it->second;std::sort(v.begin(),v.end(),[](const auto&a,const auto&b){return a.qe-a.qs>b.qe-b.qs;});const auto&m=v.front();int a=m.ts,b=m.te;for(auto&h:v)if(h.t==m.t&&h.rev==m.rev){a=std::min(a,h.ts);b=std::max(b,h.te);}auto contig=ctg.find(m.t);if(contig!=ctg.end()&&a>=0&&b<=(int)contig->second.size()){auto n=contig->second.substr(a,b-a);if(m.rev)n=rc(std::move(n));if(double(n.size())/std::max(1,m.ql)>.9)kv.second=std::move(n);}}
 std::ifstream gi(gfa);std::ofstream go(out);std::string l;while(std::getline(gi,l)){auto t=split(l);if(!t.empty()&&t[0]=="S"&&t.size()>=3&&ed.count(t[1])){t[2]=ed[t[1]];for(size_t i=0;i<t.size();i++)go<<(i?"\t":"")<<t[i];go<<'\n';}else go<<l<<'\n';}}
void finalize_no_scaffold(const fs::path&contigs,const fs::path&graph,const fs::path&gfa,const fs::path&repeatStats,const fs::path&outDir){fs::copy_file(contigs,outDir/"assembly.fasta",fs::copy_options::overwrite_existing);fs::copy_file(graph,outDir/"assembly_graph.gv",fs::copy_options::overwrite_existing);fs::copy_file(gfa,outDir/"assembly_graph.gfa",fs::copy_options::overwrite_existing);fs::copy_file(repeatStats,outDir/"assembly_info.txt",fs::copy_options::overwrite_existing);}
}
